version: '3'

services:
  n0t3b00k-checker:
    build: .
    # The checker runs a HTTP interface, so we need to map port 5499 to the outside (port 8000).
    ports:
      - 8000:5499
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
