#version: '2.1'

services:
  whatsscam-checker:
    build: .
    # The checker runs an HTTP interface, so we need to map port 5008 to the outside (port 8000).
    ports:
      - "19696:19696"
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=whatsscam-mongo
      - MONGO_PORT=27017
      - MONGO_USER=whatsscam
      - MONGO_PASSWORD=whatsscam
    restart: "unless-stopped"
    
  whatsscam-mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: whatsscam
      MONGO_INITDB_ROOT_PASSWORD: whatsscam
    restart: "unless-stopped"

